@startuml

title __BETTINGAUTHORITIYAPI's Class Diagram__\n

  namespace bettingauthoritiyAPI {
    class bettingauthoritiyAPI.BetLoggingAuthority {
        + addAcceptedBet()
        + endBettingRound()
        + handInGamblingCard()
        + handOutGamblingCard()
        + startBettingRound()
    }
  }
  

  namespace bettingauthoritiyAPI {
    class bettingauthoritiyAPI.BetToken {
        - bettingRoundID : BettingRoundID
        - creationTime : Instant
        - uniqueTokenID : UUID
        + BetToken()
        + compareTo()
        + equals()
        + getBettingRoundID()
        + getCreationTime()
        + getUniqueTokenID()
        + hashCode()
    }
  }
  

  namespace bettingauthoritiyAPI {
    class bettingauthoritiyAPI.BetTokenAuthority {
        + getBetToken()
        + getRandomInteger()
    }
  }
  

  namespace bettingauthoritiyAPI {
    class bettingauthoritiyAPI.BettingAuthority {
        {static} - logging : IBetLoggingAuthority
        {static} - token : IBetTokenAuthority
        + BettingAuthority()
        + getLoggingAuthority()
        + getTokenAuthority()
    }
  }
  

  namespace bettingauthoritiyAPI {
    interface bettingauthoritiyAPI.IBetLoggingAuthority {
        {abstract} + addAcceptedBet()
        {abstract} + endBettingRound()
        {abstract} + handInGamblingCard()
        {abstract} + handOutGamblingCard()
        {abstract} + startBettingRound()
    }
  }
  

  namespace bettingauthoritiyAPI {
    interface bettingauthoritiyAPI.IBetTokenAuthority {
        {abstract} + getBetToken()
        {abstract} + getRandomInteger()
    }
  }
  

  bettingauthoritiyAPI.BetLoggingAuthority .up.|> IBetLoggingAuthority
  bettingauthoritiyAPI.BetToken .up.|> Comparable
  bettingauthoritiyAPI.BetTokenAuthority .up.|> IBetTokenAuthority


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
